---
name: Build Ghostty

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:trixie
    env:
      ZIG_VERSION: 0.13.0
      GHOSTTY_VERSION: 1.1.3
    steps:
      - uses: actions/checkout@v4

      - name: setup env
        shell: bash
        run: |
          echo "ZIG_DIST=zig-linux-x86_64-${ZIG_VERSION}" | tee --append ${GITHUB_ENV}
          echo "GHOSTTY_DIST=ghostty-v${GHOSTTY_VERSION}" | tee --append ${GITHUB_ENV}

      - name: get system dependencies
        shell: bash
        run: |
          apt update
          apt --yes dist-upgrade
          apt --yes install libgtk-4-dev libadwaita-1-dev git wget xz-utils tree

      - name: get Zig
        shell: bash
        run: |
          wget --no-verbose "https://ziglang.org/download/${ZIG_VERSION}/${ZIG_DIST}.tar.xz"
          tar -xf "${ZIG_DIST}.tar.xz"

      - name: get Ghostty
        shell: bash
        run: |
          wget --no-verbose "https://github.com/ghostty-org/ghostty/archive/refs/tags/v${GHOSTTY_VERSION}.tar.gz"
          tar -xzf "v${GHOSTTY_VERSION}.tar.gz"

      - name: compile
        shell: bash
        run: |
          cd "ghostty-${GHOSTTY_VERSION}"
          ../${ZIG_DIST}/zig build -Doptimize=ReleaseFast
          cd ..

      - name: build package
        shell: bash
        run: |
          set -x
          PKG_VERSION="${GHOSTTY_VERSION}-${{ github.run_number }}.${{ github.run_attempt }}"
          sed -i -r "s/Version:/& ${PKG_VERSION}/" DEBIAN/control
          cat DEBIAN/control
          mkdir -p deb/usr/local
          cp -R DEBIAN deb/
          # tree -d
          mv ghostty-${GHOSTTY_VERSION}/zig-out/* deb/usr/local
          dpkg-deb --build deb "ghostty_${PKG_VERSION}_amd64.deb"

      - uses: actions/upload-artifact@v4
        with:
          path: "ghostty_*.deb"
